# Generated by Django 2.2.6 on 2019-10-09 19:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthsday', models.DateTimeField(default=django.utils.timezone.now)),
                ('discount', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('address', models.CharField(blank=True, max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sallers', models.ManyToManyField(to='BasicBusinessManager.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('decription', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sale_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('discount', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('products', models.ManyToManyField(to='BasicBusinessManager.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('deliver_date', models.DateTimeField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('address_of_delivery', models.CharField(blank=True, max_length=60)),
                ('notes', models.CharField(max_length=100)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='BasicBusinessManager.Client')),
                ('deliverant', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='BasicBusinessManager.Company')),
                ('products', models.ManyToManyField(to='BasicBusinessManager.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('birthsday', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('orders_delivered', models.ManyToManyField(to='BasicBusinessManager.Order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workplace', models.ManyToManyField(to='BasicBusinessManager.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=60)),
                ('company_owned', models.ManyToManyField(to='BasicBusinessManager.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='businesses_owner',
            field=models.ManyToManyField(to='BasicBusinessManager.CompanyOwner'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ManyToManyField(to='BasicBusinessManager.Sector'),
        ),
    ]
