# Generated by Django 2.2.6 on 2019-10-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='decription',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
