# Generated by Django 2.2.6 on 2019-10-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0002_auto_20191009_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyowner',
            name='company_owned',
            field=models.ManyToManyField(blank=True, to='BasicBusinessManager.Company'),
        ),
    ]
