# Generated by Django 2.2.6 on 2019-10-10 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0004_auto_20191009_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthsday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='orders_delivered',
            field=models.ManyToManyField(blank=True, to='BasicBusinessManager.Order'),
        ),
    ]
