# Generated by Django 2.2.6 on 2019-10-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0005_auto_20191010_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='BasicBusinessManager.Role'),
        ),
    ]
