# Generated by Django 2.2.6 on 2019-10-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0007_auto_20191010_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_date',
            new_name='delivery_date',
        ),
    ]
