# Generated by Django 2.2.6 on 2019-10-15 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0008_auto_20191010_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BasicBusinessManager.Role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_per_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='workplace',
            field=models.ManyToManyField(blank=True, to='BasicBusinessManager.Company'),
        ),
    ]
