# Generated by Django 2.2.6 on 2019-11-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0009_auto_20191015_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='birthsday',
            new_name='birthday',
        ),
    ]
