# Generated by Django 2.2.6 on 2019-11-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0010_auto_20191102_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birthsday',
            new_name='birthday',
        ),
    ]
