# Generated by Django 2.2.6 on 2019-11-04 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0012_auto_20191102_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BasicBusinessManager.Client'),
        ),
    ]
