# Generated by Django 2.2.6 on 2019-11-04 20:46

import BasicBusinessManager.models.users.employee
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0013_auto_20191104_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='years_employed',
            field=models.DateField(default=BasicBusinessManager.models.users.employee.Employee.count_years_employed, editable=False),
        ),
    ]
