# Generated by Django 2.2.6 on 2019-11-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0014_employee_years_employed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='years_employed',
        ),
    ]
