# Generated by Django 2.2.6 on 2019-11-19 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0017_auto_20191104_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='companyowner',
            name='birthday',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
