# Generated by Django 2.2.6 on 2019-11-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0021_auto_20191126_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
