# Generated by Django 2.2.6 on 2019-11-26 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0022_auto_20191126_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BasicBusinessManager.Client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BasicBusinessManager.Company'),
        ),
    ]
