# Generated by Django 2.2.6 on 2019-11-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0025_auto_20191126_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='workplace',
            field=models.ManyToManyField(to='BasicBusinessManager.Company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BasicBusinessManager.Client'),
        ),
    ]
