# Generated by Django 2.2.6 on 2019-11-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0026_auto_20191127_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='orders_delivered',
        ),
        migrations.AddField(
            model_name='employee',
            name='orders_delivered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BasicBusinessManager.Order'),
        ),
    ]
