# Generated by Django 2.2.6 on 2019-11-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0027_auto_20191127_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='orders_delivered',
        ),
        migrations.AddField(
            model_name='employee',
            name='orders_delivered',
            field=models.ManyToManyField(blank=True, to='BasicBusinessManager.Order'),
        ),
    ]
