# Generated by Django 2.2.6 on 2020-01-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBusinessManager', '0028_auto_20191127_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='_order_products_+', to='BasicBusinessManager.Product'),
        ),
    ]
